apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylab-cafe-app
  labels:
     app: cafe-app

spec:
  replicas: 2
  selector:
    matchLabels:
      app: cafe-app

  template:
    metadata:
      labels:
        app: cafe-app
    spec:
      containers:
      - name: cafe-app
        image: ashfaque9x/cafe-app
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

Refer---https://kubernetes.io/docs/tutorials/services/connect-applications-service/
$ nano cafe-app-service.yml
apiVersion: v1
kind: Service
metadata:
  name: mylab-service
  labels:
    app: cafe-app
spec:
  selector:
    app: cafe-app 

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer
